StockManagement/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockManagement.Data;
using StockManagement.Models;
using StockManagement.Services;

namespace StockManagement.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly IArticleRepository _repo;

        public ArticlesController(IArticleRepository repo)
        {
            _repo = repo;
        }

        // GET: Articles
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetAll());
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _repo.FindById((int)id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Articles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Libelle,SKU,DateSortie,PrixInitial,Poids")] Article article)
        {
            if (ModelState.IsValid)
            {
                _repo.Insert(article);
                await _repo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _repo.FindById((int)id);
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Libelle,SKU,DateSortie,PrixInitial,Poids")] Article article)
        {
            if (id != article.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _repo.Update(article);
                    await _repo.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _repo.FindById((int)id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _repo.FindById(id);
            _repo.Remove(article);
            await _repo.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleExists(int id)
        {
            return _repo.Exists(id);
        }
    }
}

StockManagement/Controllers/EtageresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockManagement.Data;
using StockManagement.Models;
using StockManagement.Services;

namespace StockManagement.Controllers
{
    public class EtageresController : Controller
    {
        private readonly IEtagereRepository _repo;
        private readonly ISecteurRepository _repoSecteur;

        public EtageresController(IEtagereRepository repo, ISecteurRepository repoSecteur)
        {
            _repo = repo;
            _repoSecteur = repoSecteur;
        }

        // GET: Etageres
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetAll());
        }

        // GET: Etageres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var etagere = await _repo.FindById((int)id);
            if (etagere == null)
            {
                return NotFound();
            }

            return View(etagere);
        }

        // GET: Etageres/Create
        public async Task<IActionResult> Create()
        {
            ViewData["SecteurId"] = new SelectList(await _repoSecteur.GetAll(), "Id", "Name");
            return View();
        }

        // POST: Etageres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PoidsMaximum,SecteurId")] Etagere etagere)
        {
            if (ModelState.IsValid)
            {
                _repo.Insert(etagere);
                await _repo.Save();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SecteurId"] = new SelectList(await _repoSecteur.GetAll(), "Id", "Name", etagere.SecteurId);
            return View(etagere);
        }

        // GET: Etageres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var etagere = await _repo.FindById((int)id);
            if (etagere == null)
            {
                return NotFound();
            }
            ViewData["SecteurId"] = new SelectList(await _repoSecteur.GetAll(), "Id", "Name", etagere.SecteurId);
            return View(etagere);
        }

        // POST: Etageres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PoidsMaximum,SecteurId")] Etagere etagere)
        {
            if (id != etagere.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _repo.Update(etagere);
                    await _repo.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EtagereExists(etagere.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SecteurId"] = new SelectList(await _repo.GetAll(), "Id", "Name", etagere.SecteurId);
            return View(etagere);
        }

        // GET: Etageres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var etagere = await _repo.FindById((int)id);
            if (etagere == null)
            {
                return NotFound();
            }

            return View(etagere);
        }

        // POST: Etageres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var etagere = await _repo.FindById(id);
            _repo.Remove(etagere);
            await _repo.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool EtagereExists(int id)
        {
            return _repo.Exists(id);
        }
    }
}

StockManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StockManagement.Models;

namespace StockManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StockManagement/Controllers/SecteursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockManagement.Data;
using StockManagement.Models;
using StockManagement.Services;

namespace StockManagement.Controllers
{
    public class SecteursController : Controller
    {
        private readonly ISecteurRepository _repo;

        public SecteursController(ISecteurRepository repo)
        {
            _repo = repo;
        }

        // GET: Secteurs
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetAll());
        }

        // GET: Secteurs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var secteur = await _repo.FindById((int)id);
            if (secteur == null)
            {
                return NotFound();
            }

            return View(secteur);
        }

        // GET: Secteurs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Secteurs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Secteur secteur)
        {
            if (ModelState.IsValid)
            {
                _repo.Insert(secteur);
                await _repo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(secteur);
        }

        // GET: Secteurs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var secteur = await _repo.FindById((int)id);
            if (secteur == null)
            {
                return NotFound();
            }
            return View(secteur);
        }

        // POST: Secteurs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Secteur secteur)
        {
            if (id != secteur.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _repo.Update(secteur);
                    await _repo.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SecteurExists(secteur.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(secteur);
        }

        // GET: Secteurs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var secteur = await _repo.FindById((int)id);
            if (secteur == null)
            {
                return NotFound();
            }

            return View(secteur);
        }

        // POST: Secteurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var secteur = await _repo.FindById(id);
            _repo.Remove(secteur);
            await _repo.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool SecteurExists(int id)
        {
            return _repo.Exists(id);
        }
    }
}

StockManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .card{
        border:none;
    }
</style>
<section id="sec-about" class="sec-about pt-5 pb-5">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-md-10 col-lg-8">
                <h1 class="h4">A propos de nous !</h1>
                <p class="mt-4 mb-4">
                    Mélanger une équipe de trois développeurs ! un travail <b>titanesque </b>! Un nombre de tasses de café <b>gigantesque</b>,
                    et vous obtenez <b>StockManagement</b>, Une application de gestion de stock merveilleuse !
                </p>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-sm-4 text-center">
                <h4>3</h4>

                <hr />

                <h5>
                    membres
                </h5>
            </div>
                
            <div class="col-sm-4 text-center">
                <h4>4</h4>

                <hr />

                <h5>espace de co-working </h5>
            </div>

            <div class="col-sm-4 text-center">
                <h4>324</h4>

                <hr />

                <h5>Tasses de café</h5>
            </div>
        </div>
    </div>
</section>

<hr />


<section id="sec-pricing" class="sec-pricing">
    <div class="container">
        <h1 class="h4 mb-5 text-center">Toutes les possibilités</h1>

        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card text-center">
                    <div class="card-block">
                        <h4 class="card-title h5">ARTICLES</h4>

                        

                        <p class="card-text">Visualisez, Ajouter, Modifier, Supprimer vos Articles !</p>


                        <a asp-controller="Articles" asp-action="Index" class="btn btn-primary">Let's Go !</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card text-center">
                    <div class="card-block">
                        <h4 class="card-title h5">ETAGERES</h4>

                        

                        <p class="card-text">Visualisez, Ajouter, Modifier, Supprimer vos Etageres !</p>


                        <a asp-controller="Etageres" asp-action="Index" class="btn btn-primary">Let's Go !</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card text-center">
                    <div class="card-block justify-content-center">
                        <h4 class="card-title h5">SECTEURS</h4>

                       

                        <p class="card-text">Visualisez, Ajouter, Modifier, Supprimer vos Secteurs !</p>

                        <a asp-controller="Secteurs" asp-action="Index" class="btn btn-primary">Let's Go !</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-center" style="margin-top:2em">
            <div class="col-md-4">

            </div>

            <div class="col-md-4" style="margin-bottom:2em;">
                <div class="card text-center">
                    <div class="card-block">
                        <h4 class="card-title h5">POSITION MAGASIN</h4>

                       

                        <p class="card-text">Gerez la position de vos articles, vous saurez au courant de tout !</p>

                        <a asp-area="" asp-controller="PositionsMagasins" asp-action="Index" class="btn btn-primary">Let's Go !</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">

            </div>
        </div>
    </div>
</section>